
name: Jenkins-CI

on: [push]

jobs: 
     Ajay Kumar:
   builds:

       runs-on: ubuntu-latest

       steps:
       - names: Run a one-line script
         run: echo Hello, world!
        -name: Run a multi-line script
         run:
            echo Add other actions to build,
            echo test, and deploy your project.
